In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =pd.read_csv('./iris.csv')

In [3]:
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.shape

(150, 6)

In [9]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [10]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
df['Species'] = df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})

In [14]:
df.info

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]>

In [15]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [17]:
x =df.iloc[:, :-1]
y =df.iloc[: , -1]

In [18]:
x.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [19]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)


In [22]:
len(x_train),len(y_train)

(100, 100)

In [23]:
len(x_test),len(y_test)

(50, 50)

## Model development

In [27]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
reg =AdaBoostClassifier(base_estimator =log,n_estimators=100, learning_rate=1.0)

In [29]:
import warnings
warnings.filterwarnings('ignore')

In [30]:
reg.fit(x_train,y_train)

AdaBoostClassifier(base_estimator=LogisticRegression(), n_estimators=100)

In [32]:
reg.score(x_train,y_train)

1.0

In [33]:
reg.score(x_test,y_test)

1.0

In [34]:
y_train_pred = reg.predict(x_train)

In [35]:
y_train_pred[:10]

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [36]:
y_train[:10]

96     1
105    2
66     1
0      0
122    2
67     1
28     0
40     0
44     0
60     1
Name: Species, dtype: int64

In [37]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix

In [38]:
accuracy_score(y_train,y_train_pred)

1.0

In [39]:
confusion_matrix(y_train,y_train_pred)

array([[31,  0,  0],
       [ 0, 35,  0],
       [ 0,  0, 34]], dtype=int64)

In [40]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



## Test performance

In [41]:
y_test_pred =reg.predict(x_test) 

In [42]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix

In [43]:
accuracy_score(y_test,y_test_pred)

1.0

In [44]:
confusion_matrix(y_test,y_test_pred)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 16]], dtype=int64)

In [45]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

